services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: node:16.20.0-alpine3.18
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

